# Generated by Django 3.0.5 on 2020-04-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0002_auto_20200416_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
