# Generated by Django 3.0.5 on 2020-04-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0004_auto_20200426_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
