# Generated by Django 3.0.5 on 2020-05-12 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0007_auto_20200512_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='DOB',
        ),
    ]
