# Generated by Django 3.0.5 on 2020-05-12 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0008_remove_users_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='add',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
    ]
