# Generated by Django 3.0.5 on 2020-05-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pal', '0009_auto_20200512_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
